# Generated by Django 5.1 on 2024-09-11 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=12)),
                ('historial_medico', models.TextField()),
                ('medicamentos', models.CharField(max_length=500)),
                ('patologia', models.CharField(max_length=100)),
                ('alergias', models.CharField(max_length=100)),
                ('progreso', models.TextField()),
                ('dispositivo_ortesis', models.CharField(max_length=100)),
                ('actividad_fisica', models.CharField(choices=[('Sedentario', 'Sedentario'), ('Moderado', 'Moderado'), ('Activo', 'Activo')], max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motivo_desvinculacion', models.CharField(choices=[('Terminó tratamiento', 'Terminó tratamiento'), ('Cambio de terapeuta', 'Cambio de terapeuta'), ('Otro', 'Otro')], max_length=500)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('angulo_inicial', models.IntegerField()),
                ('angulo_final', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('fecha', models.DateField()),
                ('duracion', models.IntegerField()),
                ('corriente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.CharField(max_length=500)),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='terapeuta.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10)),
            ],
        ),
    ]
