# Generated by Django 5.0.6 on 2024-09-24 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=12, null=True)),
                ('historial_medico', models.TextField(blank=True, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=500, null=True)),
                ('patologia', models.CharField(blank=True, max_length=100, null=True)),
                ('alergias', models.CharField(blank=True, max_length=100, null=True)),
                ('progreso', models.TextField(blank=True, null=True)),
                ('dispositivo_ortesis', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad_fisica', models.CharField(blank=True, choices=[('Sedentario', 'Sedentario'), ('Moderado', 'Moderado'), ('Activo', 'Activo')], max_length=100, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('motivo_desvinculacion', models.CharField(blank=True, choices=[('Terminó tratamiento', 'Terminó tratamiento'), ('Cambio de terapeuta', 'Cambio de terapeuta'), ('Otro', 'Otro')], max_length=500, null=True)),
                ('date_joined', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('angulo_inicial', models.IntegerField()),
                ('angulo_final', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('fecha', models.DateField()),
                ('duracion', models.IntegerField()),
                ('corriente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.CharField(max_length=500)),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='terapeuta.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Medianamente Disponible', 'Medianamente Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=30)),
                ('horas_trabajadas', models.FloatField(default=0)),
                ('fecha_contratacion', models.DateField()),
                ('titulo', models.CharField(default='Sin título', max_length=100)),
                ('experiencia', models.IntegerField(blank=True, null=True)),
                ('presentacion', models.CharField(default='¡Hola! Soy tu terapeuta. Estoy aquí para ayudarte a mejorar tu calidad de vida. ¡Vamos a trabajar juntos!', max_length=500)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.terapeuta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.terapeuta'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('sala', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.paciente')),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.terapeuta')),
            ],
        ),
    ]
