# Generated by Django 5.1 on 2024-09-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0002_citas'),
        ('terapeuta', '0002_remove_terapeuta_nombre_remove_terapeuta_rut_and_more'),
    ]

    operations = [
    ]
