# Generated by Django 5.1 on 2024-09-19 22:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0003_merge_20240916_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Medianamente Disponible', 'Medianamente Disponible'), ('No Disponible', 'No Disponible')], default=datetime.time(9, 0), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='horas_trabajadas',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes_am_ini', models.TimeField()),
                ('lunes_am_fin', models.TimeField()),
                ('lunes_pm_ini', models.TimeField()),
                ('lunes_pm_fin', models.TimeField()),
                ('martes_am_ini', models.TimeField()),
                ('martes_am_fin', models.TimeField()),
                ('martes_pm_ini', models.TimeField()),
                ('martes_pm_fin', models.TimeField()),
                ('miercoles_am_ini', models.TimeField()),
                ('miercoles_am_fin', models.TimeField()),
                ('miercoles_pm_ini', models.TimeField()),
                ('miercoles_pm_fin', models.TimeField()),
                ('jueves_am_ini', models.TimeField()),
                ('jueves_am_fin', models.TimeField()),
                ('jueves_pm_ini', models.TimeField()),
                ('jueves_pm_fin', models.TimeField()),
                ('viernes_am_ini', models.TimeField()),
                ('viernes_am_fin', models.TimeField()),
                ('viernes_pm_ini', models.TimeField()),
                ('viernes_pm_fin', models.TimeField()),
                ('sabado_am_ini', models.TimeField()),
                ('sabado_am_fin', models.TimeField()),
                ('sabado_pm_ini', models.TimeField()),
                ('sabado_pm_fin', models.TimeField()),
                ('domingo_am_ini', models.TimeField()),
                ('domingo_am_fin', models.TimeField()),
                ('domingo_pm_ini', models.TimeField()),
                ('domingo_pm_fin', models.TimeField()),
                ('id_terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapeuta.terapeuta')),
            ],
        ),
    ]
