# Generated by Django 5.1 on 2024-09-21 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0004_rename_fecha_ingreso_terapeuta_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terapeuta.terapeuta')),
            ],
        ),
    ]
