# Generated by Django 5.1 on 2024-09-23 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0005_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Medianamente Disponible', 'Medianamente Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=30),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='horas_trabajadas',
            field=models.FloatField(default=0),
        ),
    ]
