# Generated by Django 5.1 on 2024-09-23 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0006_terapeuta_disponibilidad_terapeuta_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AddField(
            model_name='paciente',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='first_name',
            field=models.CharField(default='Juanito', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='last_name',
            field=models.CharField(default='Perez', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='12345678-9', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Femenino', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='actividad_fisica',
            field=models.CharField(blank=True, choices=[('Sedentario', 'Sedentario'), ('Moderado', 'Moderado'), ('Activo', 'Activo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dispositivo_ortesis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='motivo_desvinculacion',
            field=models.CharField(blank=True, choices=[('Terminó tratamiento', 'Terminó tratamiento'), ('Cambio de terapeuta', 'Cambio de terapeuta'), ('Otro', 'Otro')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='patologia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='progreso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
