# Generated by Django 5.1 on 2024-09-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_remove_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
