# Generated by Django 5.1 on 2024-09-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcionista',
            old_name='fecha_ingreso',
            new_name='fecha_contratacion',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='estado',
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='formacion_academica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=100, null=True),
        ),
    ]
